Add Nunchuk connection details
getumbrel/umbrel-dashboard pull request #403
Opened 2022-02-07 03:47 UTC by bakaoh

Adds connection instructions for Nunchuk Wallet (using Electrum)

2022-02-07 14:18 UTC, lukechilds approved these changes

2022-02-07 15:01 UTC, lukechilds commented on src/components/ConnectWallet/Wallets/Nunchuk.vue
> +        Go to <span class="font-weight-bold">"Settings"</span>.
On mobile this is called "Account" not "Settings".

2022-02-07 15:04 UTC, lukechilds commented on src/components/ConnectWallet/Wallets/Nunchuk.vue
> +        Disable <span class="font-weight-bold">"Set SSL Certificate"</span>.
This doesn't appear for me on mobile.

2022-02-07 15:05 UTC, lukechilds commented on src/components/ConnectWallet/Wallets/Nunchuk.vue
> +        Close <span class="font-weight-bold">"Settings"</span>
On mobile you need to click "Save netowrk settings" not close.

2022-02-07 15:06 UTC, lukechilds requested changes
It looks like the instructions are different for mobile and desktop. Maybe we should list them seperately?

Also, is Tor supposed to work on mobile? It doesn't appear to work for me.

2022-02-08 03:14 UTC, hugohn commented
@lukechilds good catch! We're actually in the middle of a desktop redesign, which includes updating the Settings screen. It will be similar to what you currently see on mobile. The desktop build with the Settings UI changes will be out in a few days. So maybe it's okay with 1 component? WDYT? 

@bakaoh let's update the copy to reflect the latest design.

As for Tor, we have not yet hooked it up to the mobile UI. It's one of our TODOs.

2022-02-08 09:41 UTC, lukechilds commented
Ok got it.

We're showing the Tor electrum address here, so bear in mind the instructions are gonna fail for mobile users currently if Tor isn't working for them. If you wanna ship it like this anyway and implement it later, that's also fine with me.

2022-02-09 09:22 UTC, merged